### ISSUE TITLE
Virtual camera doesn't render streams in web app

### ISSUE THREAD

**Issue by csuft** [Niap/OBS-VirtualCam-sender#1]
Hi, the source code works if I preview virtual camera in Zoom on macOS,  but it doesn't work on web app. Here is how to reproduce the issue:
1. Open web app in Google Chrome: https://webcamtests.com/
2. Select my virtual camera in web page
3. Start OBS-VirtualCam-sender in XCode, the frames are sent successfully, but the streams can't show up in web page
4. Even if I stream to virtual camera bundled in OBS Studio, it doesn't work either.

My os version is macOS Big Sur 11.2 in a mini box. I can't figure it out why.

**Comment by Niap** [comment]
It does not support WebRTC, but OBS itself does.I'll find some time to see what's going on.

**Comment by Niap** [comment]
1.  OBS-Studio's MACH_SERVICE_NAME has ben modified. So I corrected the right one.
2. WebRTC need client to provide current time stamp , Zoom and other apps dost not. 

@csuft Please try the latest version , If not working let me know. thanks.

**Comment by csuft** [comment]
Thank you so much, it works like a charm.
