### ISSUE TITLE
do i still compile the obs-virtual-cam code ?

### ISSUE THREAD

**Issue by Linkersem** [Niap/OBS-VirtualCam-sender#2]
Thanks for your geat work! I find the notice "Notice: obs-studio have officially provided virtual camera feature since version 26.0.0 , you can use it without installing this plugin",do i still compile the obs  obs-virtual-cam code?

**Comment by Niap** [comment]
> Thanks for your geat work! I find the notice "Notice: obs-studio have officially provided virtual camera feature since version 26.0.0 , you can use it without installing this plugin",do i still compile the obs obs-virtual-cam code?

No, You can just install the obs-studio client.
